# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-22 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='description',
            new_name='plan',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='location',
        ),
    ]
