# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-22 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_auto_20190722_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trips',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
